/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InputDialog: typeof import('./src/components/InputDialog.vue')['default']
    QuestionDialog: typeof import('./src/components/QuestionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarProvider: typeof import('./src/components/SnackbarProvider.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
